### ISSUE TITLE
The tree-sitter-go can not parse the type of string.

### ISSUE THREAD

**Issue by GoneZ5** [cedricrupb/code_tokenize#2]
Hi, when I parse the `go` function, the string value can not be parsed. Can you help me?

![image](https://user-images.githubusercontent.com/62784442/163096682-36796944-a3ab-49cf-bb07-b4829337d53b.png)

![image](https://user-images.githubusercontent.com/62784442/163096635-6fee0fb0-b3f8-423b-9984-714e42a1dbba.png)

Thank you in advance!

**Comment by cedricrupb** [comment]
Hey, sorry for the delayed reply.

Sadly, this is actually a problem of unconventional handling of strings by tree-sitter for Go. Since the strings are represented
as `interpreted_string_literal` instead of `string` which breaks the string handling during tokenization.

In the current version, there is no easy workaround. However, I am working hard on version 0.2 which will make it much easier
to integrate custom behavior for tokenization.

**Comment by cedricrupb** [comment]
Should be closed in version 0.2.0. Please reopen if necessary.
